### ISSUE TITLE
Grand Theft Auto IV - Bloat

### ISSUE THREAD

**Issue by Zorklis** [neatodev/InstallDebloater#14]
Game is 22.4 GB.
Has a 208 MB "Redistributables" folder for Rockstar Launcher and Social Club Setup.
Also has Manuals folder that's 35.7 MB in size.
Has yet another Redistributables folder inside the GTAIV folder.
It takes up 196 MB of space, has same launchers.
Game now takes up 22.0 GB

**Comment by EV3RGR33N** [comment]
Hi there,
I'll make a template for both IV and V soon. I just need to test if launching the game reacquires the Social Club Installer - if I recall, it does whenever there's a new version of the RGL or SC. The manuals and other redists can be removed without issue though. 
Have a nice day!

**Comment by EV3RGR33N** [comment]
Hi there,
Sorry for answering so late. I made a template for IV early June but I probably made a mistake somewhere and it wasn't pushed to the repo.
It's not as good as I'd want it to be though - IV has a bunch of manuals that can be removed as well as Rockstar Game Launcher stuff. The later are about 200mb and will be redownloaded every time they are updated, which happens every two week or so. 
Have a nice day!
